name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # State management
  provider: ^6.1.2

  http: ^1.3.6

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Local storage
  shared_preferences: ^2.2.2

  # Media & permissions
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1

  # Cloud storage
  cloudinary_flutter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/FitnessAppModel.png
    - lib/assets/FitnessAppModel2.png
    - lib/assets/blabla.jpg
    
